from ..checksum.cm_base import CMBase
from ..io.io_base import IODataBase

class HashBase:
    def __init__(self, key_coder:CMBase):...
    def json_save(self, path): ...
    def __getitem__ (self, key: int):...
    def __setitem__ (self, key: int, data: IODataBase):...
    def __delitem__ (self, key: int):...
    